---
title: "Coursera_Causality_Week3"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Coursera: Crash Course Causal Inference
Week 3 - Programming assignment

Load the packages and lalonde data:
```{r}
install.packages("tableone")

install.packages("Matching")

install.packages("MatchIt")

library(tableone)

library(Matching)

library(MatchIt)

data(lalonde)
```
### Question 1

```{r}
xvars = colnames(lalonde)
xvars = xvars[2:(length(xvars)-1)]

table1 = CreateTableOne(vars = xvars,  
                        strata = "treat",
                        data = lalonde,
                        test = FALSE)
print(table1, 
      smd = TRUE)
```

### Question 2

```{r}
-6984.17 + 6349.14
```

### Question 3

```{r}
treat = lalonde$treat
age = lalonde$age
educ = lalonde$educ
black = lalonde$black
hispan = lalonde$hispan
married = lalonde$married
nodegree = lalonde$nodegree
re74 = lalonde$re74
re75 = lalonde$re75

out = lalonde$re78
  
psmodel = glm(treat ~ age + educ + black + hispan + married + nodegree + re74 + re75,
              family = binomial(link = logit),
              data = lalonde)

min(psmodel$fitted.values)
max(psmodel$fitted.values)
```


### Question 4

```{r}
library(car)

set.seed(931139)

psmatch = Match(Tr = lalonde$treat,
                M = 1,
                X = psmodel$fitted.values,
                replace = FALSE)

matched = lalonde[unlist(psmatch[c("index.treated", "index.control")]), ]

matchedtable1 = CreateTableOne(vars = xvars,
                               strata = "treat",
                               data = matched,
                               test = FALSE)

print(matchedtable1, 
      smd = TRUE)
```


### Question 6

Divide by 2:
```{r}
dim(matched)
```


### Question 7

```{r}
set.seed(931139)

psmatch = Match(Tr = lalonde$treat,
                M = 1,
                X = psmodel$fitted.values,
                replace = FALSE,
                caliper = 0.1)

matched = lalonde[unlist(psmatch[c("index.treated", "index.control")]), ]

matchedtable1 = CreateTableOne(vars = xvars,
                               strata = "treat",
                               data = matched,
                               test = FALSE)

print(matchedtable1, 
      smd = TRUE)

mean(matched[matched$treat==1, ]$re78)-mean(matched[matched$treat==0, ]$re78)

```

### Question 8

```{r}
yt = matched[matched$treat==1, ]$re78
yc = matched[matched$treat==0, ]$re78

diffe = yt - yc

t.test(diffe)




```
